config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  devise_for :users, skip: :registration
  resources :users
  resources :briefcases do
    resources :documents
  end
  resources :tec_leaders do
    collection { post :import}
  end
  resources :certifications
  resources :dependences do
    collection { post :import}
  end
  get '/import', to: 'tec_leaders#import_file'
  get '/import_dependence', to: 'dependences#import_file'
end

app/views/shared/_alert.html.haml
-if devise_error_messages!.present?
  .row.justify-content-center
    .col-6
      .alert.alert-danger.alert-dismissible.fade.show
        = devise_error_messages!
        %button.close{ 'data-dismiss': 'alert' }
          %span x
-else
  .row.justify-content-center
    .col-6
      #error_explanation
        .alert.alert-danger.alert-dismissible.fade.show
          %h5.text-center= "¡ #{flash.alert} !"
          %button.close{ 'data-dismiss': 'alert' }
            %span x

app/views/shared/_alerterror.html.haml
.alert.alert-danger.alert-dismissible.fade.show
	= flash[:alert]
	%button.close{ 'data-dismiss': 'alert' }
		%span x
		/ #error= render 'shared/alerterror' if (flash[:alert])

app/views/shared/_alertsuccess.html.haml
.alert.alert-success.alert-dismissible.fade.show
  = notice
  %button.close{ 'data-dismiss': 'alert' }
    %span x

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to root_path, class: 'navbar-brand' do
    = image_tag 'beca-logo.png', alt: '', height: '40', width: '40', class: 'd-inline-block'
    %span{class:'font-italic font-weight-bold'} Gestión de Requerimientos
  %button{class: 'navbar-toggler collapsed', type: 'button', 'data-toggle'=>'collapse', 'data-target'=>"#navbarSupportedContent", 'aria-controls'=>"navbarSupportedContent", 'aria-expanded'=>"false", 'aria-label'=>"Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarSupportedContent
    %ul{class:'navbar-nav mr-auto'}
      %li{class:'nav-item'}
        = link_to root_path, class:'nav-link' do
          Requerimientos
      %li{class:'nav-item'}
        = link_to root_path, class:'nav-link' do
          Certificaciones
      %li{class:'nav-item'}
        = link_to root_path, class:'nav-link disabled' do
          Estadísticas
      - if current_user.role == 'administrator'
        %li{class:'nav-item dropdown'}
          %a{href:"#", class:'nav-link dropdown-toggle', id:"adminusers", role:"button", 'data-toggle'=>"dropdown", 'aria-haspopup'=>"true", 'aria-expanded'=>"false"}
            Manejo de Usuarios
          .dropdown-menu{"aria-labelledby" => "adminusers"}
            = link_to new_user_path, class: 'dropdown-item' do
              Crear Usuario
            = link_to users_path, class: 'dropdown-item' do
              Manejo de Usuarios
    -# %form.form-inline.my-2.my-lg-0
    -#   %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
    -#   %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
    -# %span Usuario:
  -# = image_tag 'beca-logo.png', alt: '', height: '30', width: '30', class: 'd-inline-block align-top'
  -if current_user.name.present?
    %ul{class:'navbar-nav mr-auto'}
      %li{class: 'nav-item dropdown'}
        = link_to "#{current_user.name}", "#", {class:'nav-link dropdown-toggle font-italic text-capitalize font-weight-bold', id:"menuperfil", role:"button", 'data-toggle'=>"dropdown", 'aria-haspopup'=>"true", 'aria-expanded'=>"false"}
        .dropdown-menu{"aria-labelledby" => "menuperfil"}
          = link_to user_path(current_user.id), class:'dropdown-item' do
            Consultar Perfil
          = link_to edit_user_path(current_user.id), class:'dropdown-item' do
            Modificar Perfil
          .dropdown-divider
          = link_to destroy_user_session_path, method: 'delete', class:'dropdown-item' do
            Cerrar Sesión
  - else
    %ul{class:'navbar-nav mr-auto'}
      %li{class: 'nav-item dropdown'}
        = link_to "#{current_user.email}", "#", {class:'nav-link dropdown-toggle font-italic font-weight-bold', id:"menuperfil", role:"button", 'data-toggle'=>"dropdown", 'aria-haspopup'=>"true", 'aria-expanded'=>"false"}
        .dropdown-menu{"aria-labelledby" => "menuperfil"}
          = link_to user_path(current_user.id), class:'dropdown-item' do
            Consultar Perfil
          = link_to edit_user_path(current_user.id), class:'dropdown-item' do
            Modificar Perfil
          .dropdown-divider
          = link_to destroy_user_session_path, method: 'delete', class:'dropdown-item' do
            Cerrar Sesión
  = image_tag 'beca-logo.png', alt: '', height: '30', width: '30', class: 'd-inline-block align-top'

app/views/shared/_navbar_left.html.haml
-# https://bootsnipp.com/snippets/featured/responsive-navigation-menu
-# .container.mt-2
-#   %h1 HOLA PEPSICOLA
.nav-side-menu
  .brand.font-italic
    = image_tag 'Logo_exterior.jpg', alt: '', height: '40', width: '40', class: 'd-inline-block'
    -# Gestión de Requerimientos
  %i.fa.fa-bars.fa-2x.toggle-btn{"data-target" => "#menu-content", "data-toggle" => "collapse"}
  .menu-list
    %ul#menu-content.menu-content.collapse.out
      %li
        = link_to root_path do
          %i.fa.fa-home.fa-lg.ml-2
          Inicio
      -# %li.collapsed.active{"data-target" => "#products", "data-toggle" => "collapse"}
      -#   -# %a{:href => "#"}
      -#   %i.fa.fa-gift.fa-lg.ml-3
      -#   %span.ml-1
      -#   UI Elements
      -#   %span.fas.fa-angle-down.icons-right
      -# %ul#products.sub-menu.collapse
      -#   %li.active
      -#     %a{:href => "#"} CSS3 Animation
      -#   %li
      -#     %a{:href => "#"} General
      -#   %li
      -#     %a{:href => "#"} Buttons
      -#   %li
      -#     %a{:href => "#"} Tabs  Accordions
      -#   %li
      -#     %a{:href => "#"} Typography
      -#   %li
      -#     %a{:href => "#"} FontAwesome
      -#   %li
      -#     %a{:href => "#"} Slider
      -#   %li
      -#     %a{:href => "#"} Panels
      -#   %li
      -#     %a{:href => "#"} Widgets
      -#   %li
      -#     %a{:href => "#"} Bootstrap Model
      %li.collapsed{"data-target" => "#portafolio", "data-toggle" => "collapse"}
        -# %a{:href => "#"}
        %i.fa.fa-briefcase.fa-lg.ml-3
        %span.ml-1
        Portafolio
        %span.fas.fa-angle-down.icons-right
      %ul#portafolio.sub-menu.collapse
        %li.active
          = link_to new_briefcase_path do
            Registrar
        %li
          = link_to briefcases_path do
            Listado
        -# %li New Service 3
      %li.collapsed{"data-target" => "#certificaciones", "data-toggle" => "collapse"}
        -# %a{:href => "#"}
        %i.fa.fa-file-contract.fa-lg.ml-3
        %span.ml-1
        Certificaciones
        %span.fas.fa-angle-down.icons-right
      %ul#certificaciones.sub-menu.collapse
        %li.active
          = link_to new_certification_path do
            Registrar
        %li
          = link_to certifications_path do
            Listado General
        %li Listado Personalizado
      - if current_user.present?
        - if current_user.role == 'administrator'
          %li.collapsed{"data-target" => "#dependence", "data-toggle" => "collapse"}
            %i.fa.fa-building.fa-lg.ml-3
            %span.ml-1
            Dependencias
            %span.fas.fa-angle-down.icons-right
          %ul#dependence.sub-menu.collapse
            %li.active
              = link_to new_dependence_path do
                Registrar
            %li
              = link_to dependences_path do
                Listado
            %li
              = link_to import_dependence_path do
                Cargar Archivo CSV
          %li.collapsed{"data-target" => "#leaders", "data-toggle" => "collapse"}
            %i.fa.fa-user-friends.fa-lg.ml-3
            %span.ml-1
            Plantilla de Líderes
            %span.fas.fa-angle-down.icons-right
          %ul#leaders.sub-menu.collapse
            %li.active
              = link_to new_tec_leader_path do
                Registrar
            %li
              = link_to tec_leaders_path do
                Listado
            %li
              = link_to import_path do
                Cargar Archivo CSV
          %li.collapsed{"data-target" => "#users", "data-toggle" => "collapse"}
            %i.fa.fa-users.fa-lg.ml-3
            %span.ml-1
            Usuarios
            %span.fas.fa-angle-down.icons-right
          %ul#users.sub-menu.collapse
            %li.active
              = link_to new_user_path do
                Registrar
            %li
              = link_to users_path do
                Listado
        %li
          = link_to edit_user_path(current_user.id) do
            %i.fa.fa-user.fa-lg.ml-2
            %span.ml-1
            Mi Perfil
      %span{id:'sing_in_btn'}
        - if !current_user.present?
          - if controller_name !='sessions'
            = link_to new_user_session_path, class: 'btn btn-sm btn-outline-warning' do
              Iniciar Sesión
          - else
            = link_to root_path, class: 'btn btn-sm btn-outline-warning' do
              Home
        -else
          = link_to destroy_user_session_path, method: 'delete', class: 'btn btn-sm btn-outline-warning' do
            Logout
-# %input{class:"dropify", type:"file"}