config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  devise_for :users, skip: :registration
  resources :users
  resources :briefcases do
    resources :documents
  end
  resources :tec_leaders do
    collection { post :import}
  end
  resources :certifications
  resources :dependences do
    collection { post :import}
  end
  get '/import', to: 'tec_leaders#import_file'
  get '/import_dependence', to: 'dependences#import_file'
end

app/models/certification.rb
class Certification < ApplicationRecord
  enum priority: [:normal, :urgente]
  enum enviorment: [:desarrollo, :calidad, :producción]
  enum status: [:pendiente, :enviada]
  belongs_to :user
  belongs_to :tec_leader
  belongs_to :dependence
  has_one_attached :document
  validate :correct_file_type

  private

  def correct_file_type
    if document.attached? && !document.content_type.in?(%w(application/pdf))
      errors.add(:document, 'Seleccionar solo archivos con la extensión .pdf')
    end
  end

end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_certification, only: [:show, :edit, :update, :destroy]
  before_action :set_user_sec, only: [:new, :edit, :create]
  before_action :set_leader_tec, only: [:new, :edit, :create]
  before_action :set_dependece, only: [:new, :edit, :create]

  def index
    @certifications = Certification.all
  end

  def new
    @certification = Certification.new
  end

  def create
    @certification = Certification.new(certification_params)
    if @certification.save
      redirect_to certifications_path, notice: "La Certificación se registró satisfactoriamente"
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @certification.update(certification_params)
      redirect_to certifications_path, notice: "La Certificación se actualizó satisfactoriamente"
    else
      render :edit
    end
  end

  def destroy
    if @certification.destroy
      redirect_to certifications_path, notice: "El Usuario ha sido eliminado"
    end
  end

  private

  def set_certification
    @certification = Certification.find(params[:id])
  end

  def certification_params
    params.require(:certification).permit(:date, :sent_date, :details, :priority, :enviorment, :status, :user_id, :tec_leader_id, :dependence_id, :document)
  end

  def set_user_sec
    @users = User.all.collect { |user| [user.name, user.id] }
  end

  def set_leader_tec
    @leaders = TecLeader.all.collect { |leader| [leader.name, leader.id] }
  end

  def set_dependece
    @dependences = Dependence.all.collect { |dependence| [dependence.name, dependence.id] }
  end
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/views/certifications/_form.html.haml
= form_with(model: @certification, local:true) do |f|
  - if @certification.errors.any?
    .row.justify-content-center
      .col-6
        #error_explanation.alert.alert-danger.alert-dismissible.fade.show
          %h4
            = pluralize(@certification.errors.count, "error")
            al intentar registrar la certificación:
          %ul
            - @certification.errors.full_messages.each do |message|
              %li= message
          %button.close{ 'data-dismiss': 'alert' }
            %span x
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :details, 'Detalles'
        = f.text_area :details, class: 'form-control', autofocus: true, autocomplete: "details"
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :priority,'Prioridad'
        = f.select :priority, Certification.priorities.keys.map { |priority| [priority.titleize, priority]}, {}, {class: 'form-control custom-select', required: 'true'}
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :enviorment,'Ambiente'
        = f.select :enviorment, Certification.enviorments.keys.map { |enviorment| [enviorment.titleize, enviorment]}, {}, {class: 'form-control custom-select', required: 'true'}
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :status,'Estatus'
        = f.select :status, Certification.statuses.keys.map { |status| [status.titleize, status]}, {}, {class: 'form-control custom-select', required: 'true'}
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :user_id,'Líder de Seguridad'
        = f.select :user_id, @users, {}, {class: 'form-control custom-select', required: 'true'}
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :tec_leader_id,'Líder Técnico'
        = f.select :tec_leader_id, @leaders, {}, {class: 'form-control custom-select', required: 'true'}
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :dependence_id,'Dependencia'
        = f.select :dependence_id, @dependences, {}, {class: 'form-control custom-select', required: 'true'}
  .form-group
    .row.justify-content-center
      .col-3
        = f.label :date, 'Fecha de Recepción'
        = f.date_field :date, class: 'form-control', autofocus: true
      .col-3
        = f.label :sent_date, 'Fecha de Entrega'
        = f.date_field :sent_date, class: 'form-control', autofocus: true
  -if action_name == 'new'
    .form-group
      .row.justify-content-center
        .col-6
          = f.label :document, 'Adjuntar Certificación'
          = f.file_field :document, class: 'form-control-file', autofocus: true, required: 'true'
  -else
    .form-group
      .row.justify-content-center
        .col-6
          = f.label :document, 'Adjuntar Certificación'
          = f.file_field :document, class: 'form-control-file', autofocus: true
  .actions.text-center
    .form-group
      .row.justify-content-center
        .col-3
          = f.submit "Guardar", class: 'btn btn-outline-primary btn-block'
        .col-3
          = link_to "Cancelar", certifications_path, class: 'btn btn-outline-danger btn-block'

app/views/certifications/edit.html.haml
.container.mt-5
  %h2{class: 'text-center'} Editar Certificación
  = render 'form'

app/views/certifications/index.html.haml
.container.mt-2.pos_relative
  %h4{class:'text-center'}Listado de Certificaciones Emitidas
  - if @certifications.present?
    %table{class: 'table table-hover', id: 'tablecertifications'}
      %thead
        %tr
          %th
            N°
          -# %th
          -#   Fecha de Recepción
          %th
            Detalles
          -# %th
          -#   Prioridad
          -# %th
          -#   Ambiente
          %th
            Estatus
          %th
            Lider de Seguridad
          %th
            Lider Técnico
          -# %th
          -#   Dependencia
          -# %th
          -#   Fecha de Envío
          %th
            Documento de Certificación
          %th
            Opción
      %tbody
        - @certifications.each do |cert|
          %tr
            %td
              = link_to "#{cert.id}", cert
            -# %td
            -#   = cert.date
            %td
              = cert.details
            -# %td
            -#   .text-capitalize= cert.priority
            -# %td
            -#   .text-capitalize= cert.enviorment
            %td
              .text-capitalize= cert.status
            %td
              = cert.user.name
            %td
              = cert.tec_leader.name
            -# %td
            -#   = cert.dependence.name
            -# %td
            -#   = cert.sent_date
            %td{class: 'text-center'}
              = link_to 'Ver', url_for(cert.document), target: "_blank"
            %td.dropdown.dropright
              %button#dropdownMenuButton.btn{class: 'btn btn-info',type: 'button', 'data-toggle':"dropdown", 'aria-haspopup': "true", 'aria-expanded': "false"}
                = image_tag 'menu.svg'
              .dropdown-menu#dropdownmenu{"aria-labelledby" => "dropdownMenuButton"}
                .dropdown-item#dropdownmenuitem
                  = link_to edit_certification_path(cert.id), class: '', id: 'optionbutton' do
                    .row
                      .col-3
                        = image_tag 'pencil.svg'
                      .col-9
                        Editar
                .dropdown-item#dropdownmenuitem
                  = link_to certification_path(cert.id), method: 'delete', data: {confirm: '¿Esta seguro de eliminar este género?'}, class: '', id: 'optionbutton' do
                    .row
                      .col-3
                        = image_tag 'bin.svg'
                      .col-9
                        Eliminar
  - else
    %h1 No Existen Registros

app/views/certifications/new.html.haml
.container.mt-5
  %h2{class: 'text-center'} Registro de Certificaciones
  = render 'form'

app/views/certifications/show.html.haml
.container.mt-2.pos_relative
  %h4{class:'text-center'}= "Certificación Número: #{@certification.id}"
  %p
    %strong Fecha de Recepción:
    = @certification.date
  %p
    %strong Detalles:
    = @certification.details
  %p
    %strong Prioridad:
    = @certification.priority
  %p
    %strong Ambiente:
    = @certification.enviorment
  %p
    %strong Estatus:
    = @certification.status
  %p
    %strong Lider de Seguridad:
    = @certification.user.name
  %p
    %strong Lider Técnico:
    = @certification.tec_leader.name
  %p
    %strong Dependencia:
    = @certification.dependence.name
  %p
    %strong Fecha de Envío:
    = @certification.sent_date
  %p
    %strong Documento de Certificación:
    = link_to 'Visualizar', url_for(@certification.document), target: "_blank"
  %p
    = link_to 'Editar', edit_certification_path(@certification), class: 'btn btn-outline-primary'
    = link_to 'Volver', certifications_path, class: 'btn btn-outline-primary'