config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  devise_for :users, skip: :registration
  resources :users
  resources :briefcases do
    resources :documents
  end
  resources :tec_leaders do
    collection { post :import}
  end
  resources :certifications
  resources :dependences do
    collection { post :import}
  end
  get '/import', to: 'tec_leaders#import_file'
  get '/import_dependence', to: 'dependences#import_file'
end

app/models/tec_leader.rb
class TecLeader < ApplicationRecord
  require 'csv'
  validates :name, presence: true

  has_many :certifications

  def self.import(file)
    if file.path.split('.').last.to_s.downcase == 'csv'
      self.check_file(file)
    else
      return false
    end
  end

  private

  def self.check_file(file)
    CSV.foreach(file.path, headers: true, encoding: 'iso-8859-1:utf-8', col_sep: ";") do |row|
      if (row.headers[0] != 'name')
        return false
      else
        if row.length > 1
          return false
        else
          if row[0].blank?
            return false
          else
            TecLeader.create! row.to_hash
          end
        end
      end
    end
    return true
  end

end

app/controllers/tec_leaders_controller.rb
class TecLeadersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :redirect_if_not_admin

  def import_file
  end

  def index
    @tecleaders = TecLeader.all
  end

  def new
    @tecleader = TecLeader.new
  end

  def create
    @tecleader = TecLeader.new(tecleader_params)
    if @tecleader.save
      flash[:notice] = "Se ha creado el registro satisfactoriamente"
      redirect_to tec_leaders_path
    else
      render :action => 'new'
    end
  end

  def edit
    @tecleader = TecLeader.find(params[:id])
  end

  def update
    @tecleader = TecLeader.find(params[:id])
    if @tecleader.update(tecleader_params)
      flash[:notice] = "Se ha actualizado el registro satisfactoriamente"
      redirect_to tec_leaders_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @tecleader = TecLeader.find(params[:id])
    if @tecleader.destroy
      flash[:notice] = "¡ El registro seleccionado, ha sido eliminado exitosamente !"
      redirect_to tec_leaders_path
    else
      redirect_to tec_leaders_path, alert: '¡ No fue posible eliminar el registro seleccionado !'
    end
  end

  def import
    if TecLeader.import(params[:file])
      redirect_to tec_leaders_path, notice: "¡ Lista de Líderes agregada correctamente !"
    else
      redirect_to root_path, alert: "¡ERROR! La lista no pudo ser agregada correctamente. Revise el formato del archivo"
    end
  end

  private

  def tecleader_params
    params.require(:tec_leader).permit(:name)
  end

  def is_admin?
    @is_admin = current_user.role == 'administrator'
  end

  def redirect_if_not_admin
    unless @is_admin then redirect_to root_path, alert: "No posees los permisos necesarios" end
  end

end

app/helpers/tec_leaders_helper.rb
module TecLeadersHelper
end

app/views/tec_leaders/_form.html.haml
= form_with(model: @tecleader, local:true) do |f|
  - if @tecleader.errors.any?
    .row.justify-content-center
      .col-6
        #error_explanation.alert.alert-danger.alert-dismissible.fade.show
          %h4
            = pluralize(@tecleader.errors.count, "error")
            al intentar registrar el líder técnico:
          %ul
            - @tecleader.errors.full_messages.each do |message|
              %li= message
          %button.close{ 'data-dismiss': 'alert' }
            %span x
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :name, 'Nombre y apellido'
        = f.text_field :name, class: 'form-control', autofocus: true, autocomplete: "name"
  .actions.text-center
    .form-group
      .row.justify-content-center
        .col-3
          = f.submit "Guardar", class: 'btn btn-outline-primary btn-block'
        .col-3
          = link_to "Cancelar", tec_leaders_path, class: 'btn btn-outline-danger btn-block'

app/views/tec_leaders/edit.html.haml
.container.mt-5
  %h2{class: 'text-center'} Editar Líder Técnico
  = render 'form'

app/views/tec_leaders/import_file.html.haml
.container.mt-5
  %h2{class: 'text-center'} Registro por lote de Líderes Técnicos
  .row.justify-content-center.text-muted.font-italic.mt-3
    .col-10
      A través de esta opción, podrás cargar por lotes, aquellos Líderes Técnicos que pertenezcan al área de Tecnología de la Información, que se encuentren asignado a los requerimientos que la División de Seguridad de la Información mantenga en su portafolio activo. Recuerda que el formato válido para agregar resgitrar la información, es solo archivos separado por comas o mejor conocido ".CSV".
  = form_with(url: import_tec_leaders_path, local:true, multipart:true) do |form|
    .form-group
      .row.justify-content-center.mt-4
        .col-6
          = form.file_field :file, class: 'dropify', required: 'true'
    .actions
      .form-group
        .row.justify-content-center.mt-4
          .col-3
            = form.submit "Guardar", class: "btn btn-outline-primary btn-block"
          .col-3
            = link_to "Cancelar", tec_leaders_path, class: 'btn btn-outline-danger btn-block'

app/views/tec_leaders/index.html.haml
.container.mt-2
  %h4{class:'text-center'}Listado de Líderes Técnicos
  - if @tecleaders.present?
    %table{class: 'table table-hover', id: 'tableleaders'}
      %thead
        %tr
          %th
            Nombre
          %th
            Editar
          %th
            Eliminar
      %tbody
        - @tecleaders.each do |leader|
          %tr
            %td
              = leader.name
            %td
              = link_to edit_tec_leader_path(leader.id) do
                Editar
            %td
              = link_to tec_leader_path(leader.id), method: :delete, data: {confirm: '¿Esta seguro de eliminar el usuario seleccionado?'} do
                Eliminar
  - else
    %h1 No Existen Registros

app/views/tec_leaders/new.html.haml
.container.mt-5
  %h2{class: 'text-center'} Registro de Líder Técnico
  = render 'form'