config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  devise_for :users, skip: :registration
  resources :users
  resources :briefcases do
    resources :documents
  end
  resources :tec_leaders do
    collection { post :import}
  end
  resources :certifications
  resources :dependences do
    collection { post :import}
  end
  get '/import', to: 'tec_leaders#import_file'
  get '/import_dependence', to: 'dependences#import_file'
end

app/models/dependence.rb
class Dependence < ApplicationRecord
  require 'csv'
  has_many :certifications

  validates :name, presence: true

  def self.import(file)
    if file.path.split('.').last.to_s.downcase == 'csv'
      self.check_file(file)
    else
      return false
    end
  end

  private

  def self.check_file(file)
    CSV.foreach(file.path, headers: true, encoding: 'iso-8859-1:utf-8', col_sep: ";") do |row|
      if (row.headers[0] != 'name')
        return false
      else
        if row.length > 1
          return false
        else
          if row[0].blank?
            return false
          else
            Dependence.create! row.to_hash
          end
        end
      end
    end
    return true
  end

end

app/controllers/dependences_controller.rb
class DependencesController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :redirect_if_not_admin
  before_action :set_dependence, only: [:edit, :update, :destroy]

  def index
    @dependences = Dependence.all
  end

  def new
    @dependence = Dependence.new
  end

  def create
    @dependence = Dependence.create(dependence_params)
    if @dependence.save
      redirect_to dependences_path, notice: "El Departamento se registró satisfactoriamente"
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @dependence.update(dependence_params)
      redirect_to dependences_path, notice: "El Departamento se actualizó correctamente"
    else
      render :edit
    end
  end

  def destroy
    if @dependence.destroy
      redirect_to dependences_path, notice: "El Departamento ha sido eliminado"
    end
  end

  def import_file

  end

  def import
    if Dependence.import(params[:file])
      redirect_to dependences_path, notice: "¡ Lista de Líderes agregada correctamente !"
    else
      redirect_to root_path, alert: "¡ERROR! La lista no pudo ser agregada correctamente. Revise el formato del archivo"
    end
  end

  private

  def dependence_params
    params.require(:dependence).permit(:name)
  end

  def set_dependence
    @dependence = Dependence.find(params[:id])
  end

  def is_admin?
    @is_admin = current_user.role == 'administrator'
  end

  def redirect_if_not_admin
    unless @is_admin then redirect_to root_path, alert: "No posees los permisos necesarios" end
  end

end

app/helpers/dependences_helper.rb
module DependencesHelper
end

app/views/dependences/_form.html.haml
= form_with(model: @dependence, local:true) do |f|
  - if @dependence.errors.any?
    .row.justify-content-center
      .col-6
        #error_explanation.alert.alert-danger.alert-dismissible.fade.show
          %h4
            = pluralize(@dependence.errors.count, "error")
            al intentar registrar la certificación:
          %ul
            - @dependence.errors.full_messages.each do |message|
              %li= message
          %button.close{ 'data-dismiss': 'alert' }
            %span x
  .form-group
    .row.justify-content-center
      .col-6
        = f.label :name, 'Nombre del Departamento'
        = f.text_field :name, class: 'form-control', autofocus: true, autocomplete: "name"
  .actions.text-center
    .form-group
      .row.justify-content-center
        .col-3
          = f.submit "Guardar", class: 'btn btn-outline-primary btn-block'
        .col-3
          = link_to "Cancelar", dependences_path, class: 'btn btn-outline-danger btn-block'

app/views/dependences/edit.html.haml
.container.mt-5
  %h2{class: 'text-center'} Editar Dependencia
  = render 'form'

app/views/dependences/import_file.html.haml
.container.mt-5
  %h2{class: 'text-center'} Registro por lote de Dependencias
  .row.justify-content-center.text-muted.font-italic.mt-3
    .col-10
      A través de esta opción, podrás cargar por lotes, aquellas dependencias (Departamentos o Secciones) que pertenezcan al área de Tecnología de la Información, a la que pertenezca el Líder Técnico asignado a los requerimientos que la División de Seguridad de la Información mantenga en su portafolio activo. Recuerda que el formato válido para agregar resgitrar la información, es solo archivos separado por comas o mejor conocido ".CSV".
  = form_with(url: import_dependences_path, local:true, multipart:true) do |form|
    .form-group
      .row.justify-content-center.mt-4
        .col-6
          = form.file_field :file, class: 'dropify', required: 'true'
    .actions
      .form-group
        .row.justify-content-center.mt-4
          .col-3
            = form.submit "Guardar", class: "btn btn-outline-primary btn-block"
          .col-3
            = link_to "Cancelar", dependences_path, class: 'btn btn-outline-danger btn-block'

app/views/dependences/index.html.haml
.container.mt-2
  %h4{class:'text-center'}Listado de Departamentos TI
  - if @dependences.present?
    %table{class: 'table table-hover', id: 'tabledependences'}
      %thead
        %tr
          %th
            Nombre
          %th
            Editar
          %th
            Eliminar
      %tbody
        - @dependences.each do |dependence|
          %tr
            %td
              = dependence.name
            %td
              = link_to edit_dependence_path(dependence.id) do
                Editar
            %td
              = link_to dependence_path(dependence.id), method: :delete, data: {confirm: '¿Esta seguro de eliminar el usuario seleccionado?'} do
                Eliminar
  - else
    %h1 No Existen Registros

app/views/dependences/new.html.haml
.container.mt-5
  %h2{class: 'text-center'} Registro de Dependencia
  = render 'form'